server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/devops-class


  datasource:
    url: jdbc:postgresql://localhost:5432/db_e_learning
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 11020315
  application:
    name: e-learning-api
